#
title: LugZe blog
email: info@lugze.org
description: >
  Linux User Group of Zenica
baseurl: "/blog"
url: "https://lugze.github.io"
github_username: lugze

# Build settings

## Permalink
permalink: /:categories/:year/:title.html

## Markdown
markdown: kramdown
theme: minima

show_excerpts: true

# Control navigation order
header_pages:
  - kategorije.md
  - msl.md
  - linux-komande.md
  - faq.md
  - arhiva.md
  - about.md

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
